### ISSUE TITLE
Can't login with Amazon Polly

### ISSUE THREAD

**Issue by Errol246** [karashiiro/TextToTalk#125]
I can't login via Amazon Polly. I put in my access code access key into the the two fields and click "save and login", but I do not get the option to choose engine, sample rate etc. Incidentally, none of the other TTS options work either. When I click system it says "this TTS provice is only supported on Windows", and I am most definitely on Windows.

**Comment by ryankhart** [comment]
I just saw this. I thought I was getting GitHub notifications for things like these, but I guess not.

I've just come back from a break from the game and had a similar problem. I don't know if this will solve it for you but try double checking that the Amazon Polly "Region" is set to the exact region you set up an access key for in the [AWS Console](https://console.aws.amazon.com/console/) -> [Your name in the top right corner of the screen] -> Security Credentials -> Access Keys. If you forget your secret key that matches your Access Key ID, then just create a new one.

**Comment by ryankhart** [comment]
If you are still experiencing this issue, you may be using the current testing version, which I found that the only likely reason why it was working for me on the testing version was because I already had my credentials stored, but when I backed up and deleted my TextToTalk config folder and tried again, I couldn't login at all.

If you are on the testing version, try reverting to the normal version by going to Dalamud Settings -> Experimental and uncheck "Get plugin testing builds". Then uninstall TextToTalk and reinstall. It should keep all of your configuration between uninstall and reinstall.

**Comment by Errol246** [comment]
Thank you. I did as you asked and it worked wonderfully :)

**Comment by Foebik** [comment]
Im having the same problem. Doubled check everything but just can seem to get it to show me the available voices. I know I have it configured correctly within Amazon Polly as I have been using the service for a few months now with other apps. Any ideas? I generated new keys even and also redid the amz CLI commands. No luck.

**Comment by Foebik** [comment]
NVM I figured it out...was the region. Even though I had the correct region that I have selected before, I had to pick a different one because the error was there was no voices in the region.. which is weird because it works fine in other apps.

**Comment by karashiiro** [comment]
Should be fixed in testing v1.17.1
