### ISSUE TITLE
Amazon Polly crash

### ISSUE THREAD

**Issue by DarkSurfer79** [karashiiro/TextToTalk#30]
Hello, first of all I would like to thank you for this plugin its absolutely amazing. I seem to be having issues with Amazon Polly text to speech crashes after I try to enable Polly. I tried reinstalling the addon and as soon as I try to switch to Polly it just crashes.

**Comment by karashiiro** [comment]
Have you put in your credentials before? If so, can you try clearing them as described [here](https://goatcorp.github.io/faq/xl_troubleshooting#q-xiv-isnt-saving-my-new-password--how-do-i-clear-my-saved-password)? The entry for that is `TextToTalk_AccessKeys_AmazonPolly`. If that isn't it, please provide a log file, that should hint at what the issue is.

See below for the log location:
![image](https://user-images.githubusercontent.com/49822414/125706021-fc202a32-0e54-49f6-af25-ccfbcbc2b1a4.png)

**Comment by DarkSurfer79** [comment]
Yes that was the issue. Thank you so much for the quick response the issue is fixed by taking the above steps. Thank you again.
