### ISSUE TITLE
Possible to not read last names?

### ISSUE THREAD

**Issue by karashiiro** [karashiiro/TextToTalk#87]
### Discussed in https://github.com/karashiiro/TextToTalk/discussions/85

<div type='discussions-op-text'>

<sup>Originally posted by **FragSauce** April  2, 2022</sup>
Hey there i really like this plugin, and i like to know who is talking since i read slow, but having to hear everyones last name takes quite long, would it be possible to get another option under the "Enable "X says: when people speak" to not include the last name and just the first name?</div>

**Comment by ryankhart** [comment]
I might be able to take a swing at this one if you haven't already started working on it. I get a little excited about text manipulation projects.

I don't feel confident enough to push to master though, so if I push a change, I'll branch first, and then let you merge if it's good, @karashiiro.

**Comment by karashiiro** [comment]
Sounds good, have at it 👍

**Comment by ryankhart** [comment]
I just learned a lot about how to build plugins, got more familiar with the TextToTalk codebase, and got the configuration part for this feature committed [here](https://github.com/karashiiro/TextToTalk/commit/f3caa5e6b881e5b1036c60520460323e11c72caf), but I have yet to start on the text manipulation to parse the first name from the last name.

Also, since FFXIV refers to them as "forename" and "surname" and because "first name" and "last name" are just western cultural terms, I took the liberty to call them "forename" and "surname" in the UI. However, I kept "First" and "Last" in the code because it made for shorter variable names.

Below is a gif of the configuration UI. I'm open to feedback on it. It does nothing currently, but that'll come in a future commit.

![Animation](https://user-images.githubusercontent.com/3673962/162605057-b61be178-944e-420e-99fe-6a695a3e0d5f.gif)

**Comment by ryankhart** [comment]
Got a pull request ready for this now. https://github.com/karashiiro/TextToTalk/pull/88

I feel so empowered now. That was my first successful coding contribution to an existing project on GitHub.

**Comment by karashiiro** [comment]
Merged, I'll haul it on the lexicon repo and make a testing release with all of the new changes soon.

**Comment by karashiiro** [comment]
Released in testing version 1.13.0.

**Comment by ryankhart** [comment]
> Also just noticed: you must have been burning the midnight oil on this one 👀 

Technically yes, but I just have a late sleep schedule this past week.

**Comment by karashiiro** [comment]
Released in stable v1.13, closing.
